settings:
  include-radar: true
  include-observations: true
  include-park-alerts: false
  periods-shown: 2      # periods always visible
  periods-more: 10      # additional periods behind the expand toggle (0 = no toggle)

locations:
  - id: pigeon-river-bridge
    name: Pigeon River Bridge
    lat: 35.775598
    lon: -83.098306
    elevation_ft: 1357

  - id: max-patch-road
    name: Max Patch Road Tentsite
    lat: 35.791980
    lon: -82.961878
    elevation_ft: 4254

  - id: hot-springs
    name: Hot Springs
    lat: 35.892572
    lon: -82.827789
    elevation_ft: 1307

  - id: hurricane-gap
    name: Hurricane Gap
    lat: 35.910367
    lon: -82.791164
    elevation_ft: 2960
  
  - id: allen-gap
    name: Allen Gap
    lat: 35.987050
    lon: -82.785390
    elevation_ft: 2226
